version: "3.9"

services:
  mongo:
    container_name: mongo_lesson
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.stats().ok' | mongo localhost:27017/test --quiet" ]
      interval: 1s
      timeout: 3s
      retries: 5
